from __future__ import annotations

import numpy as np


def _defineboxes(
    positions: np.ndarray,  # type: ignore[type-arg]
    cutoff: float,
    refcell: np.ndarray,  # type: ignore[type-arg]
) -> np.ndarray:  # type: ignore[type-arg]
    """Istanciates a box around the atoms.

    For every atom in the system this function instanciates
    a box inside the reference cell centered on the atom with sides
    equal to 2*cutoff. If the box will be placed outside the reference cell
    the part that comes out will be fixed on the other side of the cell in
    order to comply with periodic boundary conditions.

    Parameters:
        positions:
            xyz coordinate for every atoms.
        cutoff:
            the max distance between the atom and a point of
            the space inside the box.
        refcell:
            Lx, Ly and Lz parameters of the reference cell.

    Returns:
        low and max limit of the box inside the reference cell
        for the three space dimensions.
    """
    # Define the number of particles
    n_parts = positions.shape[0]
    # Define the results array shapes
    boxparameters = np.zeros((n_parts, 6))
    for p in range(n_parts):
        # Define an internal cursor
        c = 0
        for d in range(3):
            # Set initial low and max box limits
            low_lim = positions[p, d] - cutoff
            max_lim = positions[p, d] + cutoff

            # box correction for low lim (periodic boundary conditions)
            if low_lim < 0:
                low_lim = refcell[d] + low_lim

            # box correction for max lim (periodic boundary conditions)
            if max_lim > refcell[d]:
                max_lim = max_lim - refcell[d]
            # Define the box parameters for the p particle
            boxparameters[p, c] = low_lim
            boxparameters[p, c + 1] = max_lim
            # Update the cursor for the next space dimension
            c += 2

    return boxparameters


def _findatomsinsidethebox(
    positions: np.ndarray,  # type: ignore[type-arg]
    boxparameters: np.ndarray,  # type: ignore[type-arg]
) -> dict[int, list[int]]:  # type: ignore[type-arg]
    """Check whitch atoms are inside the boxes.

    Takes the boxes generated by :func:`.defineboxes` and check which atoms
    are inside.

    Parameters:
        positions:
            xyz coordinate for every atoms.
        boxparameters:
            box coordinates (retuned by :func:`.defineboxes`)

    Returns:
        Python dict with the list of all atoms inside each box.
    """
    boxpop: dict[int, list[int]] = {
        particle: [] for particle in range(positions.shape[0])
    }
    for box in range(positions.shape[0]):
        if boxparameters[box, 0] > boxparameters[box, 1]:
            in_box_x = np.logical_or(
                positions[:, 0] > boxparameters[box, 0],
                positions[:, 0] < boxparameters[box, 1],
            )
        else:
            in_box_x = np.logical_and(
                positions[:, 0] >= boxparameters[box, 0],
                positions[:, 0] <= boxparameters[box, 1],
            )

        if boxparameters[box, 2] > boxparameters[box, 3]:
            in_box_y = np.logical_or(
                positions[:, 1] > boxparameters[box, 2],
                positions[:, 1] < boxparameters[box, 3],
            )
        else:
            in_box_y = np.logical_and(
                positions[:, 1] >= boxparameters[box, 2],
                positions[:, 1] <= boxparameters[box, 3],
            )

        if boxparameters[box, 4] > boxparameters[box, 5]:
            in_box_z = np.logical_or(
                positions[:, 2] > boxparameters[box, 4],
                positions[:, 2] < boxparameters[box, 5],
            )
        else:
            in_box_z = np.logical_and(
                positions[:, 2] >= boxparameters[box, 4],
                positions[:, 2] <= boxparameters[box, 5],
            )

        in_box_all = np.logical_and(
            np.logical_and(in_box_x, in_box_y), in_box_z
        )

        boxpop[box] = np.where(in_box_all)[0].tolist()

    return boxpop

def _compute_distances(positions, boxpop, refcell):
    distances = {}
    for key, values in boxpop.items():
        # Estrai le posizioni delle particelle di interesse
        pos_key = positions[key]
        pos_values = positions[values]

        #print(f"\nProcessing particle {key} against particles {values}:")

        # Calcola le differenze vettoriali tenendo conto delle PBC
        diff = pos_values - pos_key
        diff_pbc = diff - np.round(diff / refcell) * refcell
        #print(f"Differences before PBC adjustment: \n{diff}")
        #print(f"Differences after PBC adjustment: \n{diff_pbc}")

        # Calcola le distanze euclidee
        dists = np.linalg.norm(diff_pbc, axis=1)
        #print(f"Calculated distances: {dists}")

        # Aggiorna il dizionario delle distanze
        distances[key] = dists.tolist()
    #print(distances)

    return distances

def _sphere_correction(boxpop: dict[int, list[int]], distances: dict[int, list[float]], cutoff: float) -> dict[int, list[int]]:
    # Dizionario per contenere il risultato del filtraggio
    filtered_boxpop = {}

    # Itera attraverso ogni chiave e valori in boxpop
    for key, values in boxpop.items():
        # Ottiene le distanze corrispondenti per la chiave attuale
        dists = distances[key]

        # Filtra gli indici degli atomi in base al cutoff delle distanze
        filtered_indices = [values[i] for i, dist in enumerate(dists) if dist < cutoff]

        # Aggiorna il dizionario filtrato con i nuovi valori
        filtered_boxpop[key] = filtered_indices

    return filtered_boxpop

def _computeavg(
    neighbors: dict[int, list[int]],  # type: ignore[type-arg]
    descriptor: np.ndarray,  # type: ignore[type-arg]
) -> np.ndarray:  # type: ignore[type-arg]
    """Averaged descriptor for atoms belonging to the same box.

    Parameters:
        neighbors:
            Box populations taken from :func:`.findatomsinsidethebox`
        descriptor:
            A general descriptor of shape (frames, particles)
            or (frames, particles, components)

    Returns:
        Averaged descriptor between atoms belonging to the same box
    """
    avg = []
    for p in range(len(descriptor)):
        neighs = neighbors[p]
        sum_value = sum(descriptor[v] for v in neighs)
        mean_value = sum_value / len(neighs)
        avg.append(mean_value)
    return np.array(avg)


def spatialaverage(
    trajectory: np.ndarray,  # type: ignore[type-arg]
    refcell: np.ndarray,  # type: ignore[type-arg]
    descriptor: np.ndarray,  # type: ignore[type-arg]
    cutoff: float,
    volume_shape: str,
) -> np.ndarray:  # type: ignore[type-arg]
    """Spatial average of a specified descriptor over a defined cubic volume.

    This function performs spatial averaging of descriptor values across
    particles located within a space region centered on the reference atom.
    The region's edge length is determined by `2 * cutoff`.
    The purpose is to smooth out descriptor values by considering
    the contributions of nearby atoms within the specified volume.

    Parameters:
        trajectory (np.ndarray):
            A numpy array of shape [frame, particles, 3],
            representing the dynamic coordinates of particles.
        refcell (np.ndarray):
            A numpy array of shape [frame, 3], containing
            the dimensions (Lx, Ly, Lz) of the reference cell at each frame of
            the simulation.
        descriptor (np.ndarray):
            A numpy array of shape [frame, particles]
            or [frame, particles, components], containing the values
            of the descriptor being analyzed. The descriptor can be a scalar
            property or a vector property of the particles.
        cutoff (float):
            Defines the radius of the cubic volume for spatial averaging,
            centered on the reference atom. The edge length of the cube
            is thus `2 * cutoff`. This parameter sets the spatial extent
            over which the descriptor values are averaged.
        volume_shape (str):
            The shape of the space region around the atom, can be:
                - "cube"
                - "sphere"

    Returns:
        np.ndarray: A numpy array containing the spatially averaged descriptor
        values. The shape of the array will maintain the original
        descriptor shape.
    """
    avg_list = []
    for t in range(descriptor.shape[0]):
        print(f"FRAME {t}")
        box_params = _defineboxes(trajectory[:, t, :], cutoff, refcell[t, 0:3])
        neigh = _findatomsinsidethebox(trajectory[:, t, :], box_params)
        #print(neigh)
        if (volume_shape == "sphere"):
            distances = _compute_distances(trajectory[:,t,:], neigh, refcell[t , 0:3])
            #print(distances)
            neigh = _sphere_correction(neigh, distances, cutoff)
            #print(neigh)
        dimension = 3
        if len(descriptor.shape) == dimension:
            avg = _computeavg(neigh, descriptor[t, :, :])
        else:
            avg = _computeavg(neigh, descriptor[t, :])
        avg_list.append(avg)
    return np.stack(avg_list)
