from __future__ import annotations

import numpy as np


def _defineboxes(
    positions: np.ndarray,  # type: ignore[type-arg]
    cutoff: float,
    refcell: np.ndarray,  # type: ignore[type-arg]
) -> np.ndarray:  # type: ignore[type-arg]
    """Istanciates a box around the atoms.

    For every atom in the system this function instanciates
    a box inside the reference cell centered on the atom with sides
    equal to 2*cutoff. If the box will be placed outside the reference cell
    the part that comes out will be fixed on the other side of the cell in
    order to comply with periodic boundary conditions.

    Parameters:
        positions:
            xyz coordinate for every atoms.
        cutoff:
            the max distance between the atom and a point of
            the space inside the box.
        refcell:
            Lx, Ly and Lz parameters of the reference cell.

    Returns:
        low and max limit of the box inside the reference cell
        for the three space dimensions.
    """
    # Define the number of particles
    n_parts = positions.shape[0]
    # Define the results array shapes
    boxparameters = np.zeros((n_parts, 6))
    for p in range(n_parts):
        # Define an internal cursor
        c = 0
        for d in range(3):
            # Set initial low and max box limits
            low_lim = positions[p, d] - cutoff
            max_lim = positions[p, d] + cutoff

            # box correction for low lim (periodic boundary conditions)
            if low_lim < 0:
                low_lim = refcell[d] + low_lim

            # box correction for low lim (periodic boundary conditions)
            if max_lim > refcell[d]:
                max_lim = max_lim - refcell[d]
            # Define the box parameters for the p particle
            boxparameters[p, c] = low_lim
            boxparameters[p, c + 1] = max_lim
            # Update the cursor for the next space dimension
            c += 2

    return boxparameters


def _findatomsinsidethebox(
    positions: np.ndarray,  # type: ignore[type-arg]
    boxparameters: np.ndarray,  # type: ignore[type-arg]
) -> dict[int, list[int]]:  # type: ignore[type-arg]
    """Check whitch atoms are inside the boxes.

    Takes the boxes generated by :func:`.defineboxes` and check which atoms
    are inside.

    Parameters:
        positions:
            xyz coordinate for every atoms.
        boxparameters:
            box coordinates (retuned by :func:`.defineboxes`)

    Returns:
        Python dict with the list of all atoms inside each box.
    """
    boxpop: dict[int, list[int]] = {
        particle: [] for particle in range(positions.shape[0])
    }
    for box in range(positions.shape[0]):
        if boxparameters[box, 0] > boxparameters[box, 1]:
            in_box_x = np.logical_or(
                positions[:, 0] > boxparameters[box, 0],
                positions[:, 0] < boxparameters[box, 1],
            )
        else:
            in_box_x = np.logical_and(
                positions[:, 0] >= boxparameters[box, 0],
                positions[:, 0] <= boxparameters[box, 1],
            )

        if boxparameters[box, 2] > boxparameters[box, 3]:
            in_box_y = np.logical_or(
                positions[:, 1] > boxparameters[box, 2],
                positions[:, 1] < boxparameters[box, 3],
            )
        else:
            in_box_y = np.logical_and(
                positions[:, 1] >= boxparameters[box, 2],
                positions[:, 1] <= boxparameters[box, 3],
            )

        if boxparameters[box, 4] > boxparameters[box, 5]:
            in_box_z = np.logical_or(
                positions[:, 2] > boxparameters[box, 4],
                positions[:, 2] < boxparameters[box, 5],
            )
        else:
            in_box_z = np.logical_and(
                positions[:, 2] >= boxparameters[box, 4],
                positions[:, 2] <= boxparameters[box, 5],
            )

        in_box_all = np.logical_and(
            np.logical_and(in_box_x, in_box_y), in_box_z
        )

        boxpop[box] = np.where(in_box_all)[0].tolist()

    return boxpop


def _computeavg(
    neighbors: dict[int, list[int]],  # type: ignore[type-arg]
    descriptor: np.ndarray,  # type: ignore[type-arg]
) -> np.ndarray:  # type: ignore[type-arg]
    """Averaged descriptor for atoms belonging to the same box.

    Parameters:
        neighbors:
            Box populations taken from :func:`.findatomsinsidethebox`
        descriptor:
            A general descriptor of shape (frames, particles)
            or (frames, particles, components)

    Returns:
        Averaged descriptor between atoms belonging to the same box
    """
    avg = []
    for p in range(len(descriptor)):
        neighs = neighbors[p]
        sum_value = sum(descriptor[v] for v in neighs)
        mean_value = sum_value / len(neighs)
        avg.append(mean_value)
    return np.array(avg)

def spatialaverage(
        trajectory: np.ndarray, # type: ignore[type-arg]
        refcell: np.ndarray, # type: ignore[type-arg]
        descriptor: np.ndarray, # type: ignore[type-arg]
        cutoff: float,
        ) -> np.ndarray: # type: ignore[type-arg]
    """Compute the spatial average for a generic descriptor.

    The values given by a generic size descriptor (frames, particles)
    or (frames, particles, components) are averaged with the same values
    of the atoms present inside a box with a side length of 2*cutoff
    and having its center at the coordinates of the reference atom.

    Parameters:
        trajectory:
            [frame, particles, 3] array containing the dynamics coordinates
        refcell:
            [frame, 3] array containing Lx, Ly and Lz parameters
            of the reference cell during the simulation time.
        descriptor:
            [frame, particles] or [frame, particles, components] array
            containing the descriptor data.
        cutoff:
            The maximum distance between the reference atom and the other
            particles taken in consideration for the spatial smoothing.

    Returns:
        The spatial averaged descriptor.
    """
    avg_list = []
    for t in range(descriptor.shape[0]):
        box_params = _defineboxes(trajectory[:,t,:], cutoff, refcell[t,0:3])
        neigh = _findatomsinsidethebox(trajectory[:,t,:], box_params)
        dimension = 3
        if(len(descriptor.shape) == dimension):
            avg = _computeavg(neigh, descriptor[t,:,:])
        else:
            avg = _computeavg(neigh, descriptor[t,:])
        avg_list.append(avg)
    return np.stack(avg_list)
